name: weather_bloc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.0
  get_it: ^7.6.7
  intl: ^0.19.0
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-Black.ttf
          - asset: fonts/Poppins-Bold.ttf
          - asset: fonts/Poppins-Light.ttf
          - asset: fonts/Poppins-Medium.ttf
          - asset: fonts/Poppins-Regular.ttf
          - asset: fonts/Poppins-SemiBold.ttf
